proc import 
	datafile = 'Concrete_Strength.xls' out= Concrete_Strength replace;
getnames=yes;
run;
proc print;
run;
data s1;
set Concrete_Strength;
Q=0;
if Age__day_ >=(91)<=183then Q=1;
if Age__day_  >=184<=274 then Q=2;
if Age__day_ >=275<=365 then Q=3;
lop=log(Concrete_compressive_strength_MP);
run;
proc print;
run;
proc univariate normal;
VAR   lop  ;
histogram /normal(mu=est sigma=est);
run;
proc univariate normal;
VAR   Concrete_compressive_strength_MP  ;
histogram /normal(mu=est sigma=est);
run;
Title 'Corr matrix for Stregnth';
proc corr;
var Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k Coarse_Aggregate___component_6__ Fine_Aggregate__component_7__kg_ Age__day_ Concrete_compressive_strength_MP Q lop ;
run;
PROC MEANS mean std stderr clm min p25 p50 p75 max n;
RUN;



proc sgscatter;
Title 'Scatter with Stregnth';
Matrix Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k Coarse_Aggregate___component_6__ Fine_Aggregate__component_7__kg_ Age__day_ Concrete_compressive_strength_MP Q lop ;
PROC REG;
MODEL  Concrete_compressive_strength_MP=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k Coarse_Aggregate___component_6__ Fine_Aggregate__component_7__kg_   Q /vif;
RUN;
PROC REG;
MODEL  Concrete_compressive_strength_MP=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k Coarse_Aggregate___component_6__ Fine_Aggregate__component_7__kg_   Q /selection = backward;
RUN;
PROC REG;
MODEL  Concrete_compressive_strength_MP=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k Coarse_Aggregate___component_6__ Fine_Aggregate__component_7__kg_   Q /selection = forward ;
RUN;
PROC REG;
MODEL  Concrete_compressive_strength_MP=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k Coarse_Aggregate___component_6__ Fine_Aggregate__component_7__kg_   Q /selection = cp;
RUN;
PROC REG;
MODEL  Concrete_compressive_strength_MP=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k Coarse_Aggregate___component_6__ Fine_Aggregate__component_7__kg_   Q /selection = RSQUARE;
RUN;
PROC REG;
MODEL  Concrete_compressive_strength_MP=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k Coarse_Aggregate___component_6__ Fine_Aggregate__component_7__kg_   Q /selection = stepwise;
RUN;
PROC REG;
MODEL  lop=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k Coarse_Aggregate___component_6__ Fine_Aggregate__component_7__kg_   Q /selection = backward;
RUN;
title 'Model with VIf and P vals outeted , 2 removed using backward, and no vif';
PROC REG;
MODEL  Concrete_compressive_strength_MP=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k     Q /r influence ;
RUN;
title'Removed one point which was both infuential and outlier';
data s2;
set s1;
if _n_ in (382) then delete;
run;
PROC REG data = s2;
MODEL  Concrete_compressive_strength_MP=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k     Q /r influence ;
RUN;
PROC REG data = s2;
MODEL  Concrete_compressive_strength_MP=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k     Q  ;
RUN;
proc reg data =s2;
MODEL  Concrete_compressive_strength_MP=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k     Q  ;
plot student.*predicted.;
plot student.*(Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k     Q );
plot npp.*student.;
RUN;
data s3;
proc surveyselect data = s2 
		out= s3 seed =23
		samprate=.7 outall;
		run;
		data s3;
		set s3;
		if selected then St=Concrete_compressive_strength_MP;
		run;
		proc print data= s3;
		run;
proc reg data =s3 plots(maxpoints=none);
model  St =Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k     Q;
output out=out1(where=(St=.))p=yhat;
run;
proc print data = out1;
run;
data s5;
set out1;
diff=Concrete_compressive_strength_MP-yhat;
tag=abs(diff);
run;
proc print data=s5;
run;
proc summary data = s5;
var diff tag;
output out= s6 std(diff)=rsme mean(tag)=mae;
proc print data =s6;
run;
proc corr data =out1;
var Cement__component_1__kg_in_a_m_3 yhat;
run;
proc reg data = s2 plots(maxpoints=none);
model Concrete_compressive_strength_MP=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k     Q;
run;
proc reg data = s2 plots(maxpoints=none);
model Concrete_compressive_strength_MP=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k     Q/p clm cli;
proc print;
run;
data pred ;
set s2;
run;
proc reg data = pred;
model   Concrete_compressive_strength_MP=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k     Q/clb cli clm;
run;
proc reg data = pred;
model   Concrete_compressive_strength_MP=Cement__component_1__kg_in_a_m_3 Blast_Furnace_Slag__component_2_ Fly_Ash__component_3__kg_in_a_m_ Water___component_4__kg_in_a_m_3 Superplasticizer__component_5__k     Q/stb;

run;


